name: geneEd
channels:
    - anaconda
    - conda-forge
dependencies:
    - python=3.7
    - bs4
    - flask
    - lxml
    - mysql-connector-python
    - pandas
    - pip
    - pip:
        - entrezpy